#!/bin/bash

npm install -g express
npm install -g nodemon
npm install socket.io

# For client code if hosted elsewhere.
npm install socket.io-client
# query server:port/socket.io/socket.io.js
# ie: http://localhost:3000/socket.io/socket.io.js
# wget file into chrome extension if needed.

#############################

## Install Redis: http://redis.io/download
wget http://redis.googlecode.com/files/redis-2.6.5.tar.gz
tar xzf redis-2.6.5.tar.gz
rm redis-2.6.5.tar.gz
cd redis-2.6.5
make

# Add commands: redis-server, redis-cli.
sudo cp src/redis-server src/redis-cli /usr/local/bin/

# Start redis server.
redis-server
# Connect to redis in shell:
#   redis-cli

#############################




